### PR TITLE
fix: Filter for rc and unstable versions

### LINKED ISSUE #322: Software Upgrade page - hide RC's and unstable versions by default
The current list of upgradable client versions is a bit much
image

### LINKED ISSUE #325: Software Upgrade page - add checkbox to show rc/unstable client versions
After #322 is merged, we should re-enable the option to show RC's on demand with a checkbox.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by davidzwa** [comment]
@all-contributors add @timmiedinnie for code

File: src/components/Settings/SoftwareUpgradeSettings.vue [hunk 1]
```diff
@@ -100,9 +100,12 @@ onMounted(async () => {
   const clientReleases = await AppService.getClientReleases();
   current.value = clientReleases.current;
   minimum.value = clientReleases.minimum;
-  releases.value = clientReleases.releases.filter(
-    (r) => minor(r.tag_name) === minor(minimum.value.tag_name)
-  );
+  releases.value = clientReleases.filter((release) => {
+    const isMinimumVersion = minor(release.tag_name) === minor(minimum.value.tag_name);
+    const isReleaseCandidate = release.prerelease && release.tag_name.includes('rc');
```
Comment (davidzwa) [inline src/components/Settings/SoftwareUpgradeSettings.vue]: Thanks for the contribution 👍🏼 Let's change the `&&` to `||`.

File: src/components/Settings/SoftwareUpgradeSettings.vue [hunk 2]
```diff
@@ -95,24 +106,34 @@ const releases = ref<IRelease[]>([]);
...
-    return isMinimumVersion && !isReleaseCandidate && !isUnstable;
-  });
+  loadedClientReleases.value = clientReleases.releases;
+
   const versionSpec = await AppService.getVersion();
   serverVersion.value = versionSpec.version;
   monsterPiVersion.value = versionSpec.monsterPi;
 });
 
+const filteredReleases = computed(() => {
```
Comment (davidzwa) [inline src/components/Settings/SoftwareUpgradeSettings.vue:123]: I've added a computed property to calculate the list on the go, this allowed implementing #325.

File: src/components/Settings/SoftwareUpgradeSettings.vue [hunk 3]
```diff
@@ -95,24 +106,34 @@ const releases = ref<IRelease[]>([]);
...
+  return loadedClientReleases.value.filter((release) => {
+    const isMinimumVersion = minor(release.tag_name) === minor(minimum.value!.tag_name);
+    const isReleaseCandidate =
+      release.prerelease ||
+      release.tag_name.includes("rc") ||
+      release.tag_name.includes("unstable");
```
Comment (davidzwa) [inline src/components/Settings/SoftwareUpgradeSettings.vue:129]: You could not have known this, but so far I've designed the releases to possibly contain the `-unstable` suffix as well. I've never had to use it so far.

File: src/components/Settings/SoftwareUpgradeSettings.vue [hunk 4]
```diff
@@ -95,24 +106,34 @@ const releases = ref<IRelease[]>([]);
...
+    const isDraft = release.draft;
```
Comment (davidzwa) [inline src/components/Settings/SoftwareUpgradeSettings.vue:130]: I've removed the double check for `release.prerelease` in the draft check.

File: src/components/Settings/SoftwareUpgradeSettings.vue [hunk 5]
```diff
@@ -95,24 +106,34 @@ const releases = ref<IRelease[]>([]);
...
+    return isMinimumVersion && (showPrereleases.value || !isReleaseCandidate) && !isDraft;
```
Comment (davidzwa) [inline src/components/Settings/SoftwareUpgradeSettings.vue:131]: The `showPrereleases` checkbox allows including prereleases, if users decide to open that back up. This escapes the prerelease filter here.

File: src/components/Settings/SoftwareUpgradeSettings.vue [hunk 6]
```diff
@@ -95,24 +106,34 @@ const releases = ref<IRelease[]>([]);
...
+  });
+});
+
 function isCurrentRelease(release: IRelease) {
-  return release.tag_name === this.current?.tag_name;
+  return release.tag_name === current.value?.tag_name;
```
Comment (davidzwa) [inline src/components/Settings/SoftwareUpgradeSettings.vue:136]: Apparently the property was not properly accessed, which explains why the `(current)` was missing.

File: src/models/server/client-releases.model.ts [hunk 7]
```diff
@@ -1,5 +1,22 @@
 export interface IRelease {
   tag_name: string;
+  prerelease: boolean;
```
Comment (davidzwa) [inline src/models/server/client-releases.model.ts:3]: This model was not finished. I did a 99% complete attempt (mostly with the help of Github Copilot, but also the network response of github itself)
